### ISSUE TITLE
Support per-Gateway LoadBalancer annotations

### ISSUE THREAD

**Issue by rg0now** [l7mp/stunner-gateway-operator#11]
Currently the recommended way to customize the LoadBalancers created by STUNner is through adding annotations to the GatewayConfig `spec.loadBalancerServiceAnnotations` field. This, however, is global, in that it affects *all* Gateways, it does not make it possible to stop STUNner from exposing a Gateway, and it does not make it possible to add labels, only annotations.

This issue is a placeholder to add another way for controlling LoadBalancers and to discuss and implement this behavior. In particular, Istio [implements](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment) a policy where annotations/labels can be added to each Gateway and these will be automatically copied into the Kubernetes services created for that Gateway.

The particular behavior (converted to STUNner) would be as follows:
* Annotations and labels on the Gateway will be copied into the Service. This allows configuring things such as Internal load balancers that read from these fields.
* STUNner offers an additional annotation to configure the generated resources: adding a special annotation `stunner.l7mp.io/service-type` controls the `Service.spec.type` field of the Service. For example, set to ClusterIP to not expose the service externally. The default is LoadBalancer.

**Comment by TheDarkula** [comment]
@rg0now I am running the latest helm chart, `stunner/stunner`, version `1.2.0`.

I see that the annotations are being passed through from the `Gateway` to the `Service`, but the labels are omitted.

I have a block like this:
```
          labels:
            pool: ip4-static
          annotations:
            lbipam.cilium.io/ips: "x.x.x.x"
```

The cilium annotation makes it through on the service that is created, but the `pool` label is not applied.

**Comment by TheDarkula** [comment]
I also found [this](https://github.com/cilium/cilium/issues/42994), which suggests using the `infrastructure` block mentioned [here](https://gateway-api.sigs.k8s.io/guides/user-guides/infrastructure/?h=infrastructure), but it seems that this is wholly ignored on the created service.

**Comment by rg0now** [comment]
Currently this is the intended behavior: labels are *not* copied from the GW to the Svc, annotations are. Note that labels manually added to the LB Service created by the operator are preserved, so this can be a quick workaround. In the long term we definitely want to support `GW.spec.infrastructure` but we need to get a better understanding of the intended semantics first; e.g., do `infrastructure.labels/annotations` are to be copied in the Service or the Deployment created by STUNner, or both? How to distinguish between labels/annotations that would apply to the Svc and those for the Deployment?

Anyway, does this issue block you from using Cilium LB? If yes, then we should prio this...

**Comment by TheDarkula** [comment]
@rg0now Ah, I see. Manually patching the service does feel a bit messy :)

Yes, it is a blocker on using it with cilium, as the annotation specifies which IP address to use, and the labels designate which IP pool to pull from.
Without both in play, it will just hang.

It does bring up a query though. 
I use traefik, and it would actually be really clean to use it with the `IngressRouteUDP` CRD.
This way, I would not need to allocate an additional `LoadBalancer` IP address.

If I did this:
```
          annotations:
            stunner.l7mp.io/service-type: ClusterIP
```

would stunner be happy to run behind traefik?

**Comment by TheDarkula** [comment]
@rg0now I just tested the running stunner behind traefik with the `IngressRouteUDP`, and it worked perfectly!

**Comment by rg0now** [comment]
Since this is a Cilium blocker, I add this to the TODO list. We should really try to clean up our annotation/label policies because what we currently have is a mess.
