### ISSUE TITLE
Use EndpointSlices for endpoint discovery

### ISSUE THREAD

**Issue by rg0now** [l7mp/stunner-gateway-operator#26]
One of STUNner's main security features is filtering client connections based on the requested peer address: STUNner permits clients to reach all the pods that belong to the backend Services in the target UDPRoute and blocks access to all other pod IPs. This feature relies on STUNner's endpoint discovery mechanism, which makes it possible for the operator to enumerate the pod IPs that belong to a backend Service.

Currently the operator uses Kubernetes Endpoints objects for endpoint discovery. Since Kubernetes v.1.21 there is a new stable API that fixes some of the scalability issues with Endpoints called [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices). New applications are encouraged to use the new API, which currently the operator does not understand.

This issue is tracking the progress on converting the operator from using Endpoints to EndpointSlices.

**Comment by levaitamas** [comment]
related to https://github.com/l7mp/stunner/issues/138
