### ISSUE TITLE
StaticService error on `master`

### ISSUE THREAD

**Issue by grrtrr** [l7mp/stunner-gateway-operator#34]
This happens on 905c993da3e5371b8b7a4afcf332cbd44edd4112, maybe I should have used a release instead of `master`.

The controller frequently fails/restarts with this error message:
```console
2023-07-25T23:20:11.098595965Z  ERROR   ctrl-runtime.controller-runtime.source  if kind is a CRD, it should be installed before calling Start   {"kind": "StaticService.stunner.l7mp.io", "error": "no matches for kind \"StaticService\" in version \"stunner.l7mp.io/v1alpha1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/source/source.go:143
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.26.0/pkg/util/wait/wait.go:235
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.26.0/pkg/util/wait/wait.go:662
k8s.io/apimachinery/pkg/util/wait.poll
        /go/pkg/mod/k8s.io/apimachinery@v0.26.0/pkg/util/wait/wait.go:596
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.26.0/pkg/util/wait/wait.go:547
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/source/source.go:136
```

**Comment by rg0now** [comment]
Thanks for the report. We have recently introduced a new StaticService resource in master and it seems that your install somehow misses the corresponding CRD. This can either be a bug in our [Helm charts](https://github.com/l7mp/stunner-helm/tree/main) or a half-upgraded cluster. 

Until we find out, a quick workaround is to install the CRDs manually:

```console
kubectl apply -f https://raw.githubusercontent.com/l7mp/stunner-helm/main/helm/stunner-gateway-operator/crds/stunner-crd.yaml
```

**Comment by grrtrr** [comment]
Thank you, bug can be closed as "my fault". I generated the Docker images for `stunner` and `stunner-gateway-operator` from github sources,
but had downloaded the Helm chart from the Helm repo, not from github.

**Comment by rg0now** [comment]
Happy this solved itself. Remember, you can always use the bleeding edge by tracking the [`dev` Helm release channel](https://github.com/l7mp/stunner/blob/main/docs/INSTALL.md#development-version).
