### ISSUE TITLE
Cluster-internal auth secret disclosure

### ISSUE THREAD

**Issue by jaynis** [l7mp/stunner-gateway-operator#43]
The secret which the stunner auth service uses in ephemeral mode to create stunner credentials is stored in a kubernetes `Secret` and referenced under `authRef:`  in the stunner `GatewayConfig`.

While processing the `Gateway` listeners the stunner gateway operator creates a `stunnerd.conf` configuration file and stores it in a kubernetes `ConfigMap`. This `ConfigMap` contains the aforementioned secret, effectively disclosing something which was previously stored as a `Secret` in a `ConfigMap` (which can be accessed with fewer privileges).

Possible solution: Store the `stunnerd.conf` in a `Secret` instead of a `ConfigMap`.

**Comment by rg0now** [comment]
Our plan is that the ConfigMap will go away eventually, hopefully before v1. 

Just to know: Is this a blocker that stops you from using STUNner, or is is just a "nice to have" feature?

**Comment by jaynis** [comment]
This is not a blocker. It just did not look right to me, therefore I decided to report it here. I did not know there is a general refactoring planned around that config anyway.

**Comment by rg0now** [comment]
Thank you for reporting this. You're right: exposing secrets in configmaps is not secure. It is important for us to know your preferences, that's why I asked. I leave this issue open so that we prioritize this before v1.
