### ISSUE TITLE
How to configure imagePullSecrets for the Dataplane?

### ISSUE THREAD

**Issue by ignatiusreza** [l7mp/stunner-gateway-operator#46]
I noticed that the `imagePullSecrets` `Deployment` config is not exposed in the `Dataplane`. Which prohibit use of authenticated pull from dockerhub and/or alternative registry, which are necessary to bypass the number of pull limit enforced on unauthenticated pulls.

**Comment by rg0now** [comment]
Sounds reasonable. We'll implement this for v1, thanks for reporting.

**Comment by rg0now** [comment]
Planned extensions in the [`v1.DataplaneSpec`](https://pkg.go.dev/github.com/l7mp/stunner-gateway-operator@v0.18.0/api/v1#DataplaneSpec):

- Add [`ImagePullSecrets`](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) from [`corev1.PodSpec`](https://pkg.go.dev/k8s.io/api/core/v1#PodSpec), an optional list of references to secrets in the same namespace to use for pulling the `stunnerd` image.
- Add [`TopologySpreadConstraints`](https://pkg.go.dev/k8s.io/api/core/v1#TopologySpreadConstraint) from `corev1.PodSpec` to describe how a group of pods ought to spread across topology domains.
- Add [`PodSecurityContext`](https://pkg.go.dev/k8s.io/api/core/v1#PodSecurityContext) to set pod-level security attributes (see discussion [here](https://discord.com/channels/945255818494902282/1233140365767344250/1233152314047725645)).

This issue will be reused to track the progress on implementing these extensions.
